"""add user role

Revision ID: 334801efbbd8
Revises: 94af2a1fc42e
Create Date: 2026-09-28 12:40:42.999302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '334801efbbd8'
down_revision: Union[str, Sequence[str], None] = '94af2a1fc42e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Users',
        sa.Column(
            'role',
            sa.String(length=100),
            nullable=False,
            server_default="user",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'role')
    # ### end Alembic commands ###
